version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sep6-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1996lwukn0z22"
s3_prefix = "sep6-backend"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
